#!/usr/bin/env python3
# Copyright (C) 2026 Shitty team
# MIT licensed
# See the file LICENSE.MIT for the full license.
#
# Embeds font files into a generated header as byte arrays. Bytes are
# emitted as string literals with three-digit octal escapes: a string
# literal lexes as one token, which keeps the multi-megabyte header cheap
# to compile, and fixed-width octal cannot swallow a following character
# the way "\x41" + "B" would.

import sys
from pathlib import Path


def encode(data, per_line=4096):
    lines = []
    for offset in range(0, len(data), per_line):
        chunk = data[offset:offset + per_line]
        lines.append('    "' + "".join(f"\\{byte:03o}" for byte in chunk) + '"')
    return "\n".join(lines)


def main():
    if len(sys.argv) < 3:
        raise SystemExit(
            "usage: generate_font_data.py <output.h> <name=path> [name=path ...]"
        )
    output = Path(sys.argv[1])
    fonts = []
    for argument in sys.argv[2:]:
        name, _, path = argument.partition("=")
        if not name or not path:
            raise SystemExit(f"invalid font specification: {argument}")
        fonts.append((name, Path(path)))

    parts = [
        "/* Generated by generate_font_data.py; do not edit. */\n"
        "\n"
        "#pragma once\n"
        "\n"
        "#include <cstddef>\n"
        "\n"
        # Guarded by name and not by the file's own #pragma once: T8 made
        # a second generated header (the embedded example config) that a
        # single translation unit includes alongside the icon one, and
        # two copies of the struct are a redefinition.
        "#ifndef SHITTY_EMBEDDED_FONT_DATA\n"
        "#define SHITTY_EMBEDDED_FONT_DATA\n"
        "struct EmbeddedFontData {\n"
        "    const unsigned char* data;\n"
        "    size_t size;\n"
        "};\n"
        "#endif\n"
    ]
    for name, path in fonts:
        data = path.read_bytes()
        parts.append(
            f"\nstatic const unsigned char {name}Bytes[] =\n"
            f"{encode(data)};\n"
            f"\n"
            f"static const EmbeddedFontData {name}{{{name}Bytes, sizeof({name}Bytes) - 1}};\n"
        )

    output.write_text("".join(parts))


if __name__ == "__main__":
    main()
